"""Add Post and Like models

Revision ID: 10eae5780708
Revises: 3eea756ff7b5
Create Date: 2025-07-25 17:25:42.943777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10eae5780708'
down_revision = '3eea756ff7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('image1', sa.String(length=200), nullable=True),
    sa.Column('alttitle1', sa.String(length=100), nullable=True),
    sa.Column('image2', sa.String(length=200), nullable=True),
    sa.Column('alttitle2', sa.String(length=100), nullable=True),
    sa.Column('image3', sa.String(length=200), nullable=True),
    sa.Column('alttitle3', sa.String(length=100), nullable=True),
    sa.Column('link1', sa.String(length=200), nullable=True),
    sa.Column('link2', sa.String(length=200), nullable=True),
    sa.Column('frase1', sa.String(length=200), nullable=False),
    sa.Column('frase2', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('like')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=50), nullable=False),
    sa.Column('image1', sa.VARCHAR(length=200), nullable=True),
    sa.Column('alttitle1', sa.VARCHAR(length=100), nullable=True),
    sa.Column('image2', sa.VARCHAR(length=200), nullable=True),
    sa.Column('alttitle2', sa.VARCHAR(length=100), nullable=True),
    sa.Column('image3', sa.VARCHAR(length=200), nullable=True),
    sa.Column('alttitle3', sa.VARCHAR(length=100), nullable=True),
    sa.Column('link1', sa.VARCHAR(length=200), nullable=True),
    sa.Column('link2', sa.VARCHAR(length=200), nullable=True),
    sa.Column('frase1', sa.VARCHAR(length=200), nullable=False),
    sa.Column('frase2', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('title', sa.VARCHAR(length=150), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=False)
    )
    op.drop_table('posts')
    op.drop_table('likes')
    # ### end Alembic commands ###
