"""crear no se

Revision ID: 64674b92ee98
Revises: 76fc82468405
Create Date: 2025-07-28 11:02:31.976689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64674b92ee98'
down_revision = '76fc82468405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.drop_table('task')
    # ### end Alembic commands ###
