"""Add likes column

Revision ID: 66693ac96f73
Revises: 5772c18c3958
Create Date: 2025-07-25 16:25:33.740346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66693ac96f73'
down_revision = '5772c18c3958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
