"""descripción del cambio

Revision ID: a98b0674290e
Revises: 64674b92ee98
Create Date: 2025-07-29 11:51:45.647892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98b0674290e'
down_revision = '64674b92ee98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label1', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('label2', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('link3', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('label3', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('link4', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('label4', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('label4')
        batch_op.drop_column('link4')
        batch_op.drop_column('label3')
        batch_op.drop_column('link3')
        batch_op.drop_column('label2')
        batch_op.drop_column('label1')

    # ### end Alembic commands ###
